-- Base de datos: transito_bot
-- Charset recomendado: utf8mb4

CREATE TABLE IF NOT EXISTS admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bot_nodes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  key_name VARCHAR(80) NOT NULL UNIQUE,
  title VARCHAR(120) NOT NULL,
  message TEXT NOT NULL,
  is_terminal TINYINT(1) NOT NULL DEFAULT 0,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bot_options (
  id INT AUTO_INCREMENT PRIMARY KEY,
  node_id INT NOT NULL,
  option_key VARCHAR(20) NOT NULL,
  label VARCHAR(200) NOT NULL,
  action_type VARCHAR(30) NOT NULL,
  action_value TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  INDEX (node_id),
  CONSTRAINT fk_bot_options_node FOREIGN KEY (node_id) REFERENCES bot_nodes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  wa_from VARCHAR(64) NOT NULL UNIQUE,
  current_node_id INT NOT NULL,
  mode VARCHAR(12) NOT NULL DEFAULT 'BOT',
  last_message TEXT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (current_node_id),
  CONSTRAINT fk_user_sessions_node FOREIGN KEY (current_node_id) REFERENCES bot_nodes(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS message_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  wa_from VARCHAR(64) NOT NULL,
  direction VARCHAR(8) NOT NULL,
  body TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (wa_from),
  INDEX (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS handoff_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  wa_from VARCHAR(64) NOT NULL,
  target_wa VARCHAR(64) NULL,
  node_id INT NULL,
  trigger_text TEXT NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'OPEN',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  closed_at DATETIME NULL,
  INDEX (wa_from),
  INDEX (target_wa),
  INDEX (status),
  CONSTRAINT fk_handoff_node FOREIGN KEY (node_id) REFERENCES bot_nodes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS handoff_messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  handoff_id INT NOT NULL,
  sender VARCHAR(10) NOT NULL,
  body TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (handoff_id),
  CONSTRAINT fk_handoff_messages FOREIGN KEY (handoff_id) REFERENCES handoff_requests(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
